name: Python

on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'
      - ".github/workflows/python.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Lint
        working-directory: python
        run: |
          pipenv install --dev
          pipenv run ruff check databend_udf
          pipenv run ruff format --check databend_udf
      - name: build
        working-directory: python
        run: |
          python -m pip install build
          python -m build

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi.org
      url: https://pypi.org/p/databend-udf/
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        working-directory: python
        run: |
          python -m pip install build
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
          skip-existing: true
